version: '2' # specify docker-compose version

# Define the services/containers to be run
services:

  x-portfolio: # name of the first service
    hostname: x-portfolio
    restart: unless-stopped
    container_name: x-portfolio
    build: ./ # specify the directory of the Dockerfile
    labels:
      - traefik.backend=x-portfolio
      - "traefik.frontend.rule=Host:daton.it,www.daton.it"
      - traefik.docker.network=traefik_proxy
      - traefik.port=80
      - com.docker.compose.project=x-portfolio
    networks:
      - traefik_proxy
      
networks:
  traefik_proxy:
    external: true
